// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class AccountCreationTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void accountCreation() {
    driver.Navigate().GoToUrl("http://localhost/addressbook/");
    driver.Manage().Window.Size = new System.Drawing.Size(1050, 708);
    driver.FindElement(By.Name("user")).SendKeys("admin");
    driver.FindElement(By.Name("pass")).SendKeys("secret");
    driver.FindElement(By.CssSelector("input:nth-child(7)")).Click();
    driver.FindElement(By.LinkText("add new")).Click();
    driver.FindElement(By.Name("firstname")).Click();
    driver.FindElement(By.Name("firstname")).SendKeys("test");
    driver.FindElement(By.Name("middlename")).SendKeys("test");
    driver.FindElement(By.Name("lastname")).SendKeys("test");
    driver.FindElement(By.Name("nickname")).SendKeys("test");
    driver.FindElement(By.Name("title")).SendKeys("testTitle");
    driver.FindElement(By.Name("company")).SendKeys("testCompany");
    driver.FindElement(By.Name("address")).SendKeys("testAddress");
    driver.FindElement(By.Name("home")).SendKeys("testHome");
    driver.FindElement(By.Name("mobile")).SendKeys("385544455");
    driver.FindElement(By.Name("work")).SendKeys("test");
    driver.FindElement(By.Name("address2")).Click();
    driver.FindElement(By.Name("address2")).SendKeys("testAddressSecond");
    driver.FindElement(By.CssSelector("input:nth-child(87)")).Click();
    driver.FindElement(By.LinkText("home page")).Click();
    driver.FindElement(By.LinkText("Logout")).Click();
  }
}
