// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
using WebAddressBookTests;


[TestFixture]
public class AccountCreationTest
{
    private IWebDriver driver;
    public IDictionary<string, object> vars { get; private set; }
    private IJavaScriptExecutor js;

    [SetUp]
    public void SetUp()
    {
        driver = new ChromeDriver();
        js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<string, object>();
    }

    [TearDown]
    protected void TearDown()
    {
        driver.Quit();
    }
    [Test]
    public void accountCreation()
    {
        OpenHomePage();
        Login(new AccountData("admin", "secret"));
        InitiateAccountCreation();
        FillAccountForms(new GroupData("NameTest"));
        GoToHomePage();
        Logout();
    }

    private void Logout()
    {
        driver.FindElement(By.LinkText("Logout")).Click();
    }

    private void GoToHomePage()
    {
        driver.FindElement(By.LinkText("home page")).Click();
    }

    private void FillAccountForms(GroupData group)
    {
        driver.FindElement(By.Name("firstname")).Click();
        driver.FindElement(By.Name("firstname")).SendKeys(group.FirstName);
        driver.FindElement(By.Name("middlename")).SendKeys(group.MiddleName);
        driver.FindElement(By.Name("lastname")).SendKeys(group.LastName);
        driver.FindElement(By.Name("nickname")).SendKeys(group.NickName);
        driver.FindElement(By.Name("title")).SendKeys(group.Title);
        driver.FindElement(By.Name("company")).SendKeys(group.Company);
        driver.FindElement(By.Name("address")).SendKeys(group.Address);
        driver.FindElement(By.Name("home")).SendKeys(group.Home);
        driver.FindElement(By.Name("mobile")).SendKeys(group.Mobile);
        driver.FindElement(By.Name("work")).SendKeys(group.Work);
        driver.FindElement(By.Name("address2")).Click();
        driver.FindElement(By.Name("address2")).SendKeys(group.Address2);
        driver.FindElement(By.CssSelector("input:nth-child(87)")).Click();
    }

    private void InitiateAccountCreation()
    {
        driver.FindElement(By.LinkText("add new")).Click();
    }

    private void Login(AccountData account)
    {
        driver.FindElement(By.Name("user")).SendKeys(account.UserName);
        driver.FindElement(By.Name("pass")).SendKeys(account.Password);
        driver.FindElement(By.CssSelector("input:nth-child(7)")).Click();
    }

    private void OpenHomePage()
    {
        driver.Navigate().GoToUrl("http://localhost/addressbook/");
        driver.Manage().Window.Size = new System.Drawing.Size(1050, 708);
    }
}
